import type { ColorFamily } from "@meridian/contracts";
import type { SeedProduct } from "../../application/ports/catalog-seed-source";
import { seedDetails } from "./details";
import { deriveMaterialIds } from "./materials";

type Variant = { id: string; sku: string; label: string; swatch: string; colorFamily: ColorFamily; material: string };

type Piece = {
  slug: string;
  name: string;
  kind: string;
  category: "seating" | "tables" | "lighting" | "storage";
  materials: string;
  story: string;
  priceEur: number;
  soldOut: boolean;
  featured: boolean;
  variants: Variant[];
};

/**
 * Ported from apps/storefront/lib/catalog.ts `pieces` (same order). Each variant additionally names its colour family
 * and material id, which the storefront only implied through labels and swatches.
 */
export const pieces: Piece[] = [
  {
    slug: "holt-sofa",
    name: "Holt",
    kind: "Three-seat sofa",
    category: "seating",
    materials: "oatmeal wool, walnut",
    story: "A three-seat sofa in wool on turned walnut legs. The wool covers come off for cleaning.",
    priceEur: 1190,
    soldOut: false,
    featured: true,
    variants: [
      { id: "oatmeal", sku: "HOLT-OAT-3", label: "Oatmeal wool", swatch: "/materials/wool-oatmeal.jpg", colorFamily: "neutral", material: "wool" },
      { id: "charcoal", sku: "HOLT-CHA-3", label: "Charcoal wool", swatch: "/materials/wool-charcoal.jpg", colorFamily: "grey", material: "wool" },
    ],
  },
  {
    slug: "nara-sofa",
    name: "Nara",
    kind: "Two-seat sofa",
    category: "seating",
    materials: "saddle leather, black steel",
    story: "A low two-seat sofa in saddle leather on a thin black steel frame.",
    priceEur: 990,
    soldOut: false,
    featured: false,
    variants: [{ id: "saddle", sku: "NARA-SAD-2", label: "Saddle leather", swatch: "/materials/leather-saddle.jpg", colorFamily: "brown", material: "leather" }],
  },
  {
    slug: "pil-lounge",
    name: "Pil",
    kind: "Lounge chair",
    category: "seating",
    materials: "camel leather, oak",
    story: "A deep lounge chair with a camel leather sling on a solid oak frame. The leather darkens with use.",
    priceEur: 490,
    soldOut: false,
    featured: true,
    variants: [{ id: "camel", sku: "PIL-CAM-1", label: "Camel leather", swatch: "/materials/leather-camel.jpg", colorFamily: "brown", material: "leather" }],
  },
  {
    slug: "soren-sofa",
    name: "Soren",
    kind: "Three-seat sofa",
    category: "seating",
    materials: "rust linen, walnut",
    story: "A three-seat sofa in linen, with walnut legs set back from the arms. The linen covers come off for cleaning.",
    priceEur: 1290,
    soldOut: false,
    featured: true,
    variants: [
      { id: "rust", sku: "SOREN-RST-3", label: "Rust linen", swatch: "/materials/wool-rust.jpg", colorFamily: "orange", material: "linen" },
      { id: "ochre", sku: "SOREN-OCH-3", label: "Ochre linen", swatch: "/materials/linen-ochre.jpg", colorFamily: "yellow", material: "linen" },
    ],
  },
  {
    slug: "vale-lounge",
    name: "Vale",
    kind: "Armchair",
    category: "seating",
    materials: "ink velvet, black oak",
    story: "A square armchair covered all over in cotton velvet, on stained black oak legs.",
    priceEur: 590,
    soldOut: false,
    featured: true,
    variants: [
      { id: "ink", sku: "VALE-INK-1", label: "Ink velvet", swatch: "/materials/velvet-ink.jpg", colorFamily: "blue", material: "velvet" },
      { id: "navy", sku: "VALE-NAV-1", label: "Navy velvet", swatch: "/materials/wool-navy.jpg", colorFamily: "blue", material: "velvet" },
    ],
  },
  {
    slug: "wren-lounge",
    name: "Wren",
    kind: "Lounge chair",
    category: "seating",
    materials: "moss wool, oak",
    story: "A low lounge chair upholstered in wool, on solid oak legs.",
    priceEur: 520,
    soldOut: false,
    featured: false,
    variants: [
      { id: "moss", sku: "WREN-MOS-1", label: "Moss wool", swatch: "/materials/wool-moss.jpg", colorFamily: "green", material: "wool" },
      { id: "oatmeal", sku: "WREN-OAT-1", label: "Oatmeal wool", swatch: "/materials/wool-oatmeal.jpg", colorFamily: "neutral", material: "wool" },
    ],
  },
  {
    slug: "sola-chair",
    name: "Sola",
    kind: "Lounge chair",
    category: "seating",
    materials: "natural cane, oatmeal linen",
    story: "A low lounge chair with a bent rattan frame and a woven cane seat, plus a loose linen cushion.",
    priceEur: 450,
    soldOut: false,
    featured: false,
    variants: [
      { id: "natural", sku: "SOLA-NAT-1", label: "Natural cane", swatch: "/materials/cane.jpg", colorFamily: "brown", material: "cane" },
      { id: "black", sku: "SOLA-BLK-1", label: "Black-stained cane", swatch: "/materials/cane-black.jpg", colorFamily: "black", material: "cane" },
    ],
  },
  {
    slug: "mar-daybed",
    name: "Mar",
    kind: "Daybed",
    category: "seating",
    materials: "ivory boucle, ash",
    story: "A daybed in ivory boucle on a pale ash frame, with one loose bolster. Long enough to lie down on.",
    priceEur: 890,
    soldOut: false,
    featured: true,
    variants: [{ id: "ivory", sku: "MAR-IVY-1", label: "Ivory boucle", swatch: "/materials/boucle-ivory.jpg", colorFamily: "white", material: "boucle" }],
  },
  {
    slug: "reed-chair",
    name: "Reed",
    kind: "Dining chair",
    category: "seating",
    materials: "olive leather, oak",
    story: "A dining chair with leather seat and back pads on a solid oak frame. It goes well with the Feld and Dune tables.",
    priceEur: 149,
    soldOut: false,
    featured: false,
    variants: [
      { id: "olive", sku: "REED-OLV-1", label: "Olive leather", swatch: "/materials/leather-olive.jpg", colorFamily: "green", material: "leather" },
      { id: "saddle", sku: "REED-SAD-1", label: "Saddle leather", swatch: "/materials/leather-saddle.jpg", colorFamily: "brown", material: "leather" },
    ],
  },
  {
    slug: "ren-chair",
    name: "Ren",
    kind: "Dining chair",
    category: "seating",
    materials: "oak, paper cord",
    story: "A dining chair with a paper-cord seat on a solid oak frame. It goes well with the Feld and Dune tables.",
    priceEur: 139,
    soldOut: false,
    featured: false,
    variants: [
      { id: "oak", sku: "REN-OAK-1", label: "Oak", swatch: "/materials/oak.jpg", colorFamily: "brown", material: "paper-cord" },
      { id: "black", sku: "REN-BLK-1", label: "Black oak", swatch: "/materials/oak-black.jpg", colorFamily: "black", material: "paper-cord" },
    ],
  },
  {
    slug: "pico-stool",
    name: "Pico",
    kind: "Side stool",
    category: "seating",
    materials: "terracotta paint, three legs",
    story: "A small painted stool on three legs. Use it as an extra seat or as a side table next to a sofa.",
    priceEur: 89,
    soldOut: false,
    featured: false,
    variants: [
      { id: "terracotta", sku: "PICO-TER-1", label: "Terracotta", swatch: "/materials/paint-terracotta.jpg", colorFamily: "orange", material: "paint" },
      { id: "clay", sku: "PICO-CLY-1", label: "Clay", swatch: "/materials/paint-clay.jpg", colorFamily: "pink", material: "paint" },
    ],
  },
  {
    slug: "bruk-stool",
    name: "Bruk",
    kind: "Side stool",
    category: "seating",
    materials: "natural cork",
    story: "A solid cork stool with a slightly concave seat. Use it as an extra seat or as a side table next to a sofa.",
    priceEur: 79,
    soldOut: false,
    featured: false,
    variants: [
      { id: "natural", sku: "BRUK-NAT", label: "Natural cork", swatch: "/materials/cork.jpg", colorFamily: "brown", material: "cork" },
      { id: "dark", sku: "BRUK-DRK", label: "Dark cork", swatch: "/materials/cork-dark.jpg", colorFamily: "brown", material: "cork" },
    ],
  },
  {
    slug: "feld-table",
    name: "Feld",
    kind: "Dining table, 220 cm",
    category: "tables",
    materials: "oak, 220 cm",
    story: "A 220 cm dining table with a 40 mm solid top on four square legs. It seats eight.",
    priceEur: 1190,
    soldOut: false,
    featured: false,
    variants: [
      { id: "oak", sku: "FELD-OAK-220", label: "Oak", swatch: "/materials/oak.jpg", colorFamily: "brown", material: "oak" },
      { id: "walnut", sku: "FELD-WAL-220", label: "Walnut", swatch: "/materials/walnut.jpg", colorFamily: "brown", material: "walnut" },
    ],
  },
  {
    slug: "dune-table",
    name: "Dune",
    kind: "Round dining table",
    category: "tables",
    materials: "bleached oak, 140 cm",
    story: "A round dining table, 140 cm across. It seats four people, or five if you squeeze.",
    priceEur: 790,
    soldOut: false,
    featured: true,
    variants: [
      { id: "bleach", sku: "DUNE-BLC-140", label: "Bleached oak", swatch: "/materials/oak-bleached.jpg", colorFamily: "neutral", material: "oak" },
      { id: "oak", sku: "DUNE-OAK-140", label: "Oak", swatch: "/materials/oak.jpg", colorFamily: "brown", material: "oak" },
    ],
  },
  {
    slug: "desk-lin",
    name: "Lin",
    kind: "Writing desk",
    category: "tables",
    materials: "walnut, brass pull",
    story: "A solid walnut writing desk with one drawer and a brass pull. The top has room for a laptop and a lamp.",
    priceEur: 590,
    soldOut: false,
    featured: false,
    variants: [{ id: "walnut", sku: "LIN-WAL-140", label: "Walnut", swatch: "/materials/walnut.jpg", colorFamily: "brown", material: "walnut" }],
  },
  {
    slug: "tor-console",
    name: "Tor",
    kind: "Console desk",
    category: "tables",
    materials: "sage paint, brass pulls",
    story: "A narrow painted console desk with two drawers and brass pulls. At 42 cm deep, it fits against a wall.",
    priceEur: 490,
    soldOut: false,
    featured: false,
    variants: [
      { id: "sage", sku: "TOR-SAG-160", label: "Sage", swatch: "/materials/paint-sage.jpg", colorFamily: "green", material: "paint" },
      { id: "forest", sku: "TOR-FOR-160", label: "Forest", swatch: "/materials/paint-forest.jpg", colorFamily: "green", material: "paint" },
    ],
  },
  {
    slug: "ash-table",
    name: "Ash",
    kind: "Coffee table",
    category: "tables",
    materials: "pale ash, 110 cm",
    story: "A low coffee table in whitewashed ash, with room for a lamp and a few books.",
    priceEur: 290,
    soldOut: false,
    featured: false,
    variants: [{ id: "ash", sku: "ASH-ASH-110", label: "Pale ash", swatch: "/materials/ash.jpg", colorFamily: "neutral", material: "ash" }],
  },
  {
    slug: "terra-table",
    name: "Terra",
    kind: "Side table",
    category: "tables",
    materials: "travertine",
    story: "A small round side table carved from solid travertine, with a thick top on a wide cylindrical base.",
    priceEur: 249,
    soldOut: false,
    featured: false,
    variants: [
      { id: "travertine", sku: "TERRA-TRV", label: "Travertine", swatch: "/materials/travertine.jpg", colorFamily: "neutral", material: "stone" },
      { id: "green", sku: "TERRA-GRN", label: "Green marble", swatch: "/materials/marble-green.jpg", colorFamily: "green", material: "stone" },
    ],
  },
  {
    slug: "loma-table",
    name: "Loma",
    kind: "Coffee table",
    category: "tables",
    materials: "pink terrazzo",
    story: "A low coffee table in polished terrazzo, with a thick top on two slab legs.",
    priceEur: 390,
    soldOut: false,
    featured: false,
    variants: [
      { id: "pink", sku: "LOMA-PNK", label: "Pink terrazzo", swatch: "/materials/terrazzo.jpg", colorFamily: "pink", material: "terrazzo" },
      { id: "grey", sku: "LOMA-GRY", label: "Grey terrazzo", swatch: "/materials/terrazzo-grey.jpg", colorFamily: "grey", material: "terrazzo" },
    ],
  },
  {
    slug: "lamp-arc",
    name: "Arc",
    kind: "Arc floor lamp",
    category: "lighting",
    materials: "black steel, linen shade",
    story: "A floor lamp with a long steel arc that holds a linen shade over a chair or sofa. The weighted base stands to one side.",
    priceEur: 219,
    soldOut: false,
    featured: false,
    variants: [
      { id: "black", sku: "ARC-BLK", label: "Black steel", swatch: "/materials/black-steel.jpg", colorFamily: "black", material: "steel" },
      { id: "brass", sku: "ARC-BRS", label: "Brass", swatch: "/materials/brass.jpg", colorFamily: "metal", material: "brass" },
    ],
  },
  {
    slug: "kite-lamp",
    name: "Kite",
    kind: "Floor lamp",
    category: "lighting",
    materials: "ochre linen, black steel",
    story: "A floor lamp with a large pleated linen shade that casts coloured light on the wall.",
    priceEur: 179,
    soldOut: false,
    featured: true,
    variants: [
      { id: "ochre", sku: "KITE-OCH", label: "Ochre linen", swatch: "/materials/linen-ochre.jpg", colorFamily: "yellow", material: "linen" },
      { id: "blush", sku: "KITE-BLS", label: "Blush linen", swatch: "/materials/glass-blush.jpg", colorFamily: "pink", material: "linen" },
    ],
  },
  {
    slug: "halo-lamp",
    name: "Halo",
    kind: "Table lamp",
    category: "lighting",
    materials: "cobalt ceramic, linen shade",
    story: "A table lamp with a hand-glazed ceramic base and a white linen shade. It fits well on a desk or bedside table.",
    priceEur: 129,
    soldOut: false,
    featured: false,
    variants: [
      { id: "cobalt", sku: "HALO-COB", label: "Cobalt", swatch: "/materials/ceramic-cobalt.jpg", colorFamily: "blue", material: "ceramic" },
      { id: "ink", sku: "HALO-INK", label: "Ink", swatch: "/materials/velvet-ink.jpg", colorFamily: "black", material: "ceramic" },
    ],
  },
  {
    slug: "pebble-lamp",
    name: "Pebble",
    kind: "Table lamp",
    category: "lighting",
    materials: "sand stoneware, linen shade",
    story: "A table lamp with a pebble-shaped stoneware base and a pleated linen shade.",
    priceEur: 119,
    soldOut: false,
    featured: false,
    variants: [
      { id: "sand", sku: "PEB-SND", label: "Sand stoneware", swatch: "/materials/stoneware.jpg", colorFamily: "neutral", material: "stoneware" },
      { id: "charcoal", sku: "PEB-CHA", label: "Charcoal stoneware", swatch: "/materials/stoneware-charcoal.jpg", colorFamily: "grey", material: "stoneware" },
    ],
  },
  {
    slug: "pendant-coil",
    name: "Coil",
    kind: "Pendant lamp",
    category: "lighting",
    materials: "blackened brass",
    story: "A pendant lamp in blackened brass. It lights a small circle on the table below.",
    priceEur: 159,
    soldOut: false,
    featured: false,
    variants: [{ id: "brass", sku: "COIL-BRS", label: "Blackened brass", swatch: "/materials/brass.jpg", colorFamily: "metal", material: "brass" }],
  },
  {
    slug: "wick-pendant",
    name: "Wick",
    kind: "Glass pendant",
    category: "lighting",
    materials: "blush glass",
    story: "A globe pendant in blush glass with a brushed brass cap. It gives a warm, soft light over a dining table.",
    priceEur: 139,
    soldOut: false,
    featured: true,
    variants: [{ id: "blush", sku: "WICK-BLS", label: "Blush glass", swatch: "/materials/glass-blush.jpg", colorFamily: "pink", material: "glass" }],
  },
  {
    slug: "nook-cabinet",
    name: "Nook",
    kind: "Two-door cabinet",
    category: "storage",
    materials: "forest paint, brass pulls",
    story: "A painted cabinet on a plinth, with two doors and three adjustable shelves inside.",
    priceEur: 690,
    soldOut: false,
    featured: true,
    variants: [
      { id: "forest", sku: "NOOK-FOR", label: "Forest", swatch: "/materials/paint-forest.jpg", colorFamily: "green", material: "paint" },
      { id: "sage", sku: "NOOK-SAG", label: "Sage", swatch: "/materials/paint-sage.jpg", colorFamily: "green", material: "paint" },
    ],
  },
  {
    slug: "cist-shelf",
    name: "Cist",
    kind: "Open bookcase",
    category: "storage",
    materials: "clay paint, open shelves",
    story: "An open bookcase in clay paint with five fixed shelves for books and bowls. Fix it to the wall.",
    priceEur: 329,
    soldOut: false,
    featured: false,
    variants: [{ id: "clay", sku: "CIST-CLY", label: "Clay", swatch: "/materials/paint-clay.jpg", colorFamily: "pink", material: "paint" }],
  },
  {
    slug: "drift-bench",
    name: "Drift",
    kind: "Hall bench",
    category: "storage",
    materials: "navy wool, walnut",
    story: "A wool-covered bench on walnut legs. Use it in the hall or at the foot of a bed.",
    priceEur: 290,
    soldOut: false,
    featured: false,
    variants: [
      { id: "navy", sku: "DRIFT-NAV", label: "Navy wool", swatch: "/materials/wool-navy.jpg", colorFamily: "blue", material: "wool" },
      { id: "ink", sku: "DRIFT-INK", label: "Ink wool", swatch: "/materials/velvet-ink.jpg", colorFamily: "blue", material: "wool" },
    ],
  },
  {
    slug: "sideboard-kiln",
    name: "Kiln",
    kind: "Sideboard",
    category: "storage",
    materials: "smoked oak",
    story: "A long sideboard in smoked oak with two sliding doors. It is sold out at the moment.",
    priceEur: 990,
    soldOut: true,
    featured: false,
    variants: [{ id: "oak", sku: "KILN-OAK", label: "Smoked oak", swatch: "/materials/oak-smoked.jpg", colorFamily: "brown", material: "oak" }],
  },
];

/** Storefront image rules: the first variant shows the hero shot, other variants `/products/<slug>-<variant>.jpg`. */
const heroImage = (slug: string) => `/products/${slug}-hero.jpg`;
const variantImage = (piece: Piece, variant: Variant) => (variant.id === piece.variants[0]?.id ? heroImage(piece.slug) : `/products/${piece.slug}-${variant.id}.jpg`);
const detailImage = (slug: string) => `/products/${slug}-detail-photo.jpg`;

export const seedProducts: SeedProduct[] = pieces.map((piece) => ({
  id: `prd_${piece.slug}`,
  slug: piece.slug,
  name: piece.name,
  kind: piece.kind,
  story: piece.story,
  categoryId: piece.category,
  materials: deriveMaterialIds(piece.materials, piece.variants.map((v) => v.label)),
  priceCents: piece.priceEur * 100,
  featured: piece.featured,
  soldOut: piece.soldOut,
  heroImageUrl: heroImage(piece.slug),
  detailImageUrl: detailImage(piece.slug),
  details: seedDetails(piece.slug),
  variants: piece.variants.map((v) => ({ id: v.id, sku: v.sku, label: v.label, colorFamily: v.colorFamily, material: v.material, swatchUrl: v.swatch, imageUrl: variantImage(piece, v) })),
}));
